accounts/urls.py
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls'))
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.PostListView.as_view(), name='list'),
    path('<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('create', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls'))
]

accounts/models.py
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models


class UserType(models.IntegerChoices):
    customer = 1, _("customer")
    admin = 2, _("admin")
    superuser = 3, _("superuser")

class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise  ValueError('email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
    
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)        
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault("type", UserType.superuser.value)
    

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    type = models.IntegerField(
        choices=UserType.choices, default=UserType.customer.value)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts", default="", blank=True)

    def __str__(self):
        return self.title

core/accounts/models.py
from typing import Any
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise  ValueError('email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)        
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

core/blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts", blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)  
    
    def __str__(self):
        return self.author  

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)
from .models import Post 
from .permissions import HasAdminAccessPermission


class PostListView(LoginRequiredMixin, ListView):
    model = Post

class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, HasAdminAccessPermission, CreateView):
    model = Post
    fields = ["title", "body"]
    success_url = '/'

class PostUpdateView(LoginRequiredMixin, HasAdminAccessPermission, UpdateView):
    model = Post
    fields = ["title", "body"]
    success_url = '/'

class PostDeleteView(LoginRequiredMixin, HasAdminAccessPermission, DeleteView):
    model = Post
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('/')

core/blog/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from .models import Post 

class PostListView(ListView):
    model = Post

class PostDetailView(DetailView):
    model = Post

class PostCreateView(CreateView):
    model = Post
    fields = ["title", "body"]
    success_url = '/'

class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "body"]
    success_url = '/'

class PostDeleteView(DeleteView):
    model = Post
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('/')

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post detail</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <h3>{{ post.body }}</h3>
    <h6>{{ post.created_on }}</h6>
</body>
</html>

blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create post</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post list</title>
</head>
<body>
    <a href="/accounts/logout/?next=/">logout</a>
    <h1>post list</h1>
    <hr>
    {% for post in object_list %}
    <div><h2><a href="{% url 'blog:detail' pk=post.id %}">{{post.title}}</a>{% if request.user.type == 2 or request.user.type == 3  %} | <a href="{% url 'blog:update' pk=post.id %}">edit</a> | <a href="{% url 'blog:delete' pk=post.id %}">delete</a> {% endif %}</h2></div>
    <h4>{{ post.body | truncatewords:21 }}...</h4>
     
    {% endfor %}
    <hr>
    <p>{% if request.user.type == 2 or request.user.type == 3  %}<a href="{% url 'blog:create' %}">create</a></p>{% endif %}
</body>
</html>

core/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post list</title>
</head>
<body>
    <a href="/accounts/login">login</a> 
    <h1>post list</h1>
    <hr>
    {% for post in object_list %}
    <div><h2><a href="{% url 'blog:detail' pk=post.id %}">{{post.title}}</a> | <a href="{% url 'blog:update' pk=post.id %}">edit</a> | <a href="{% url 'blog:delete' pk=post.id %}">delete</a> </h2></div>
    <h4>{{ post.body | truncatewords:21 }}...</h4>
     
    {% endfor %}
    <hr>
    <p><a href="{% url 'blog:create' %}">create</a></p>
</body>
</html>